/**
 * generateScript(config) → string
 *
 * Pure function: takes a config object and returns a complete,
 * self-contained bash script string. No I/O.
 */

import { CACHE_MAX_AGE, LOCK_MAX_AGE, DEFAULT_CONFIG } from './defaults.js'

const BAR_STYLES = {
  thin:  { filled: '━', empty: '─' },
  dot:   { filled: '●', empty: '○' },
  block: { filled: '█', empty: '░' },
}

const COLOR_SCHEMES = {
  default: {
    C_RESET:      "\\033[0m",
    C_BOLD:       "\\033[1m",
    C_DIM:        "\\033[2m",
    C_PURPLE:     "\\033[38;5;141m",
    C_BLUE:       "\\033[38;5;75m",
    C_GREEN:      "\\033[38;5;114m",
    C_YELLOW:     "\\033[38;5;221m",
    C_RED:        "\\033[38;5;204m",
    C_GRAY:       "\\033[38;5;245m",
    C_GRAY_LIGHT: "\\033[38;5;250m",
    C_CYAN:       "\\033[38;5;116m",
    C_ORANGE:     "\\033[38;5;215m",
  },
  'traffic-light': {
    C_RESET:      "\\033[0m",
    C_BOLD:       "\\033[1m",
    C_DIM:        "\\033[2m",
    C_PURPLE:     "\\033[38;5;114m",  // green
    C_BLUE:       "\\033[38;5;114m",  // green
    C_GREEN:      "\\033[38;5;114m",
    C_YELLOW:     "\\033[38;5;221m",
    C_RED:        "\\033[38;5;204m",
    C_GRAY:       "\\033[38;5;245m",
    C_GRAY_LIGHT: "\\033[38;5;250m",
    C_CYAN:       "\\033[38;5;114m",  // green
    C_ORANGE:     "\\033[38;5;221m",  // yellow
  },
  monochrome: {
    C_RESET:      "",
    C_BOLD:       "",
    C_DIM:        "",
    C_PURPLE:     "",
    C_BLUE:       "",
    C_GREEN:      "",
    C_YELLOW:     "",
    C_RED:        "",
    C_GRAY:       "",
    C_GRAY_LIGHT: "",
    C_CYAN:       "",
    C_ORANGE:     "",
  },
}

function has(fields, name) {
  return fields.includes(name)
}

export function generateScript(config) {
  const {
    fields = DEFAULT_CONFIG.fields,
    separator = DEFAULT_CONFIG.separator,
    colorScheme = DEFAULT_CONFIG.colorScheme,
    barStyle = DEFAULT_CONFIG.barStyle,
    thresholds = DEFAULT_CONFIG.thresholds,
  } = config

  const colors = COLOR_SCHEMES[colorScheme] || COLOR_SCHEMES.default
  const bar = BAR_STYLES[barStyle] || BAR_STYLES.thin
  const needsRate = has(fields, 'rateBar') || has(fields, 'resetTimes')

  const lines = []
  const push = (s) => lines.push(s)

  // ── Preamble ────────────────────────────────────────────────────────────
  push(`#!/bin/bash`)
  push(`# cc-statusline — generated by cc-statusline wizard`)
  push(`# https://github.com/syuurio/cc-statusline`)
  push(``)

  // Colors
  push(`# Colors`)
  for (const [name, val] of Object.entries(colors)) {
    if (val === '') {
      push(`${name}=''`)
    } else {
      push(`${name}=$'${val}'`)
    }
  }
  push(``)

  // Icons / Separator
  push(`# Icons / Separator`)
  push(`ICON_MODEL="🤖"`)
  push(`ICON_SEPARATOR="${separator}"`)
  push(``)

  // Thresholds
  push(`# Thresholds`)
  push(`USAGE_WARN=${thresholds.warn}`)
  push(`USAGE_DANGER=${thresholds.danger}`)
  push(``)

  // Cache settings (needed if rate limit fields are selected)
  if (needsRate) {
    push(`# Cache settings`)
    push(`CACHE_DIR="\${XDG_CACHE_HOME:-$HOME/.cache}/cc-statusline"`)
    push(`USAGE_CACHE="$CACHE_DIR/usage.json"`)
    push(`USAGE_LOCK="$CACHE_DIR/.fetch.lock"`)
    push(`CACHE_MAX_AGE=${CACHE_MAX_AGE}`)
    push(`LOCK_MAX_AGE=${LOCK_MAX_AGE}`)
    push(``)
  }

  // Platform detection
  push(`# Platform detection`)
  push(`_IS_MACOS=0`)
  push(`[[ "$(uname -s)" == "Darwin" ]] && _IS_MACOS=1`)
  push(``)

  // ── Helper functions ────────────────────────────────────────────────────
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(`# HELPER FUNCTIONS`)
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(``)

  // get_file_mtime (needed for cache age checks)
  if (needsRate) {
    push(`get_file_mtime() {`)
    push(`    if [[ "$_IS_MACOS" == "1" ]]; then`)
    push(`        stat -f '%m' "$1" 2>/dev/null || echo 0`)
    push(`    else`)
    push(`        stat -c '%Y' "$1" 2>/dev/null || echo 0`)
    push(`    fi`)
    push(`}`)
    push(``)
  }

  // format_tokens (needed if tokens field is selected)
  if (has(fields, 'tokens')) {
    push(`format_tokens() {`)
    push(`    local num=$1`)
    push(`    if [[ -z "$num" ]] || [[ "$num" == "null" ]]; then`)
    push(`        echo "0"`)
    push(`        return`)
    push(`    fi`)
    push(`    if [[ "$num" -ge 1000000 ]]; then`)
    push(`        printf "%.1fM" "$(echo "scale=1; $num / 1000000" | bc)"`)
    push(`    elif [[ "$num" -ge 1000 ]]; then`)
    push(`        printf "%.1fK" "$(echo "scale=1; $num / 1000" | bc)"`)
    push(`    else`)
    push(`        echo "$num"`)
    push(`    fi`)
    push(`}`)
    push(``)
  }

  // get_usage_color (needed for bars)
  if (has(fields, 'ctxBar') || needsRate) {
    push(`get_usage_color() {`)
    push(`    local pct=$1`)
    push(`    if [[ -z "$pct" ]]; then`)
    push(`        echo "$C_GRAY"`)
    push(`    elif [[ "$pct" -ge "$USAGE_DANGER" ]]; then`)
    push(`        echo "$C_RED"`)
    push(`    elif [[ "$pct" -ge "$USAGE_WARN" ]]; then`)
    push(`        echo "$C_YELLOW"`)
    push(`    else`)
    push(`        echo "$C_GREEN"`)
    push(`    fi`)
    push(`}`)
    push(``)
  }

  // progress_bar (needed for any bar)
  if (has(fields, 'ctxBar') || has(fields, 'rateBar')) {
    push(`progress_bar() {`)
    push(`    local pct=\${1:-0}`)
    push(`    local width=\${2:-5}`)
    push(`    [[ "$pct" -lt 0 ]] && pct=0`)
    push(`    [[ "$pct" -gt 100 ]] && pct=100`)
    push(`    local filled=$((pct * width / 100))`)
    push(`    local empty=$((width - filled))`)
    push(`    local bar=""`)
    push(`    for ((i=0; i<filled; i++)); do bar+="${bar.filled}"; done`)
    push(`    for ((i=0; i<empty; i++)); do bar+="${bar.empty}"; done`)
    push(`    echo "$bar"`)
    push(`}`)
    push(``)
  }

  // format_reset_time (needed for resetTimes)
  if (has(fields, 'resetTimes')) {
    push(`format_reset_time() {`)
    push(`    local iso="$1" fmt="$2"`)
    push(`    [[ -z "$iso" ]] || [[ "$iso" == "null" ]] && return`)
    push(`    local epoch`)
    push(`    if [[ "$_IS_MACOS" == "1" ]]; then`)
    push(`        epoch=$(python3 -c "from datetime import datetime; print(int(datetime.fromisoformat('$iso').timestamp()))" 2>/dev/null) || return`)
    push(`        date -r "$epoch" +"$fmt" 2>/dev/null`)
    push(`    else`)
    push(`        if date -d "$iso" +"$fmt" 2>/dev/null; then`)
    push(`            return`)
    push(`        fi`)
    push(`        epoch=$(python3 -c "from datetime import datetime; print(int(datetime.fromisoformat('$iso').timestamp()))" 2>/dev/null) || return`)
    push(`        date -d "@$epoch" +"$fmt" 2>/dev/null`)
    push(`    fi`)
    push(`}`)
    push(``)
  }

  // ── Credential & fetch functions ────────────────────────────────────────
  if (needsRate) {
    push(`# ══════════════════════════════════════════════════════════════════`)
    push(`# CREDENTIAL & USAGE FETCH`)
    push(`# ══════════════════════════════════════════════════════════════════`)
    push(``)
    push(`get_access_token() {`)
    push(`    if command -v security &>/dev/null; then`)
    push(`        local json`)
    push(`        json=$(security find-generic-password -s "Claude Code-credentials" -w 2>/dev/null) || true`)
    push(`        if [[ -n "$json" ]]; then`)
    push(`            local token`)
    push(`            token=$(echo "$json" | jq -r '.claudeAiOauth.accessToken // empty' 2>/dev/null)`)
    push(`            [[ -n "$token" ]] && echo "$token" && return 0`)
    push(`        fi`)
    push(`    fi`)
    push(`    local cred="$HOME/.claude/.credentials.json"`)
    push(`    if [[ -f "$cred" ]]; then`)
    push(`        jq -r '.claudeAiOauth.accessToken // empty' "$cred" 2>/dev/null`)
    push(`        return`)
    push(`    fi`)
    push(`    return 1`)
    push(`}`)
    push(``)
    push(`fetch_usage_bg() {`)
    push(`    if [[ -d "$USAGE_LOCK" ]]; then`)
    push(`        local lock_age=$(( $(date +%s) - $(get_file_mtime "$USAGE_LOCK") ))`)
    push(`        if [[ "$lock_age" -ge "$LOCK_MAX_AGE" ]]; then`)
    push(`            rmdir "$USAGE_LOCK" 2>/dev/null || true`)
    push(`        else`)
    push(`            return 0`)
    push(`        fi`)
    push(`    fi`)
    push(`    mkdir "$USAGE_LOCK" 2>/dev/null || return 0`)
    push(`    (`)
    push(`        trap 'rmdir "$USAGE_LOCK" 2>/dev/null' EXIT`)
    push(`        local token`)
    push(`        token=$(get_access_token) || { return; }`)
    push(`        local tf`)
    push(`        tf=$(mktemp "$CACHE_DIR/tok.XXXXXX")`)
    push(`        chmod 600 "$tf"`)
    push(`        printf 'Authorization: Bearer %s' "$token" > "$tf"`)
    push(`        local resp`)
    push(`        resp=$(curl -s --max-time 5 "https://api.anthropic.com/api/oauth/usage" \\`)
    push(`            -H @"$tf" \\`)
    push(`            -H "anthropic-beta: oauth-2025-04-20" 2>/dev/null)`)
    push(`        rm -f "$tf"`)
    push(`        if [[ -n "$resp" ]] && echo "$resp" | jq -e '.five_hour' > /dev/null 2>&1; then`)
    push(`            resp=$(echo "$resp" | jq ". + {\\"fetched_at\\": $(date +%s)}")`)
    push(`            local tmp`)
    push(`            tmp=$(mktemp "$CACHE_DIR/cache.XXXXXX")`)
    push(`            echo "$resp" > "$tmp" && mv "$tmp" "$USAGE_CACHE"`)
    push(`        fi`)
    push(`    ) & disown`)
    push(`}`)
    push(``)
    push(`get_usage_data() {`)
    push(`    if [[ -f "$USAGE_CACHE" ]]; then`)
    push(`        cat "$USAGE_CACHE"`)
    push(`        local age=$(( $(date +%s) - $(get_file_mtime "$USAGE_CACHE") ))`)
    push(`        if [[ "$age" -ge "$CACHE_MAX_AGE" ]]; then`)
    push(`            fetch_usage_bg`)
    push(`        fi`)
    push(`    else`)
    push(`        fetch_usage_bg`)
    push(`        echo '{}'`)
    push(`    fi`)
    push(`}`)
    push(``)
  }

  // ── Main logic ──────────────────────────────────────────────────────────
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(`# MAIN LOGIC`)
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(``)

  if (needsRate) {
    push(`mkdir -p "$CACHE_DIR"`)
    push(`chmod 700 "$CACHE_DIR"`)
    push(``)
  }

  push(`input=$(cat)`)
  push(`_jq() { echo "$input" | jq -r "$1" 2>/dev/null; }`)
  push(``)

  // Parse only the fields we need
  if (has(fields, 'model')) {
    push(`model=$(_jq '.model.display_name // empty')`)
  }
  if (has(fields, 'dir') || has(fields, 'git')) {
    push(`cwd=$(_jq '.workspace.current_dir // empty')`)
  }
  if (has(fields, 'ctxBar')) {
    push(`remaining_pct=$(_jq '.context_window.remaining_percentage // empty')`)
  }
  if (has(fields, 'tokens')) {
    push(`total_input=$(_jq '.context_window.total_input_tokens // 0')`)
    push(`total_output=$(_jq '.context_window.total_output_tokens // 0')`)
    push(`context_size=$(_jq '.context_window.context_window_size // 200000')`)
  }
  if (has(fields, 'cost')) {
    push(`session_cost=$(_jq '.cost.total_cost_usd // 0')`)
  }
  push(``)

  // Context usage calculation
  if (has(fields, 'ctxBar')) {
    push(`if [[ -n "$remaining_pct" ]]; then`)
    push(`    used_pct=$(printf "%.0f" "$(echo "100 - $remaining_pct" | bc)" 2>/dev/null) || used_pct=0`)
    push(`else`)
    push(`    used_pct=0`)
    push(`fi`)
    push(``)
  }

  if (has(fields, 'tokens')) {
    push(`total_tokens=$(( \${total_input:-0} + \${total_output:-0} ))`)
    push(``)
  }

  // Fetch API usage
  if (needsRate) {
    push(`usage_data=$(get_usage_data)`)
    push(`_jqu() { echo "$usage_data" | jq -r "$1" 2>/dev/null; }`)
    push(``)
  }
  if (has(fields, 'rateBar')) {
    push(`five_hour_pct=$(_jqu '.five_hour.utilization // empty')`)
    push(`seven_day_pct=$(_jqu '.seven_day.utilization // empty')`)
  }
  if (has(fields, 'resetTimes')) {
    // Also need the pct for the conditional display
    if (!has(fields, 'rateBar')) {
      push(`five_hour_pct=$(_jqu '.five_hour.utilization // empty')`)
    }
    push(`five_hour_reset=$(_jqu '.five_hour.resets_at // empty')`)
    push(`seven_day_reset=$(_jqu '.seven_day.resets_at // empty')`)
    push(`five_reset_fmt=$(format_reset_time "\${five_hour_reset:-}" "%H:%M %-d %b")`)
    push(`seven_reset_fmt=$(format_reset_time "\${seven_day_reset:-}" "%H:%M %-d %b")`)
  }
  push(``)

  // ── Build output ────────────────────────────────────────────────────────
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(`# BUILD OUTPUT`)
  push(`# ══════════════════════════════════════════════════════════════════`)
  push(``)
  push(`line1=""`)
  push(`line2=""`)
  push(`line3=""`)
  push(`SEP=" \${C_GRAY}\${ICON_SEPARATOR}\${C_RESET} "`)
  push(``)

  // ── LINE 1 ──────────────────────────────────────────────────────────────
  push(`# LINE 1: Info fields`)

  let line1First = true

  if (has(fields, 'model')) {
    push(`if [[ -n "$model" ]]; then`)
    push(`    short_model=$(echo "$model" | sed 's/Claude //')`)
    push(`    line1+="\${C_PURPLE}\${ICON_MODEL} \${short_model}\${C_RESET}"`)
    push(`fi`)
    line1First = false
  }

  if (has(fields, 'dir')) {
    push(`if [[ -n "$cwd" ]]; then`)
    if (!line1First) {
      push(`    line1+="\${SEP}\${C_BLUE}$(basename "$cwd")\${C_RESET}"`)
    } else {
      push(`    line1+="\${C_BLUE}$(basename "$cwd")\${C_RESET}"`)
    }
    push(`fi`)
    line1First = false
  }

  if (has(fields, 'git')) {
    push(`if [[ -n "$cwd" ]] && [[ -d "$cwd" ]]; then`)
    push(`    git_branch=$(git -C "$cwd" branch --show-current 2>/dev/null)`)
    push(`    if [[ -n "$git_branch" ]]; then`)
    push(`        git_status=$(git -C "$cwd" status --porcelain 2>/dev/null)`)
    push(`        if [[ -n "$git_status" ]]; then`)
    if (!line1First) {
      push(`            line1+="\${SEP}\${C_YELLOW}\${git_branch}*\${C_RESET}"`)
    } else {
      push(`            line1+="\${C_YELLOW}\${git_branch}*\${C_RESET}"`)
    }
    push(`        else`)
    if (!line1First) {
      push(`            line1+="\${SEP}\${C_GREEN}\${git_branch}\${C_RESET}"`)
    } else {
      push(`            line1+="\${C_GREEN}\${git_branch}\${C_RESET}"`)
    }
    push(`        fi`)
    push(`    fi`)
    push(`fi`)
    line1First = false
  }

  if (has(fields, 'tokens')) {
    push(`formatted_tokens=$(format_tokens "$total_tokens")`)
    push(`formatted_max=$(format_tokens "$context_size")`)
    if (!line1First) {
      push(`line1+="\${SEP}\${C_CYAN}\${formatted_tokens}/\${formatted_max}\${C_RESET}"`)
    } else {
      push(`line1+="\${C_CYAN}\${formatted_tokens}/\${formatted_max}\${C_RESET}"`)
    }
    line1First = false
  }

  if (has(fields, 'cost')) {
    push(`if [[ -n "$session_cost" ]] && [[ "$session_cost" != "0" ]]; then`)
    push(`    formatted_cost=$(printf "%.2f" "$session_cost")`)
    if (!line1First) {
      push(`    line1+="\${SEP}\${C_ORANGE}\\$\${formatted_cost}\${C_RESET}"`)
    } else {
      push(`    line1+="\${C_ORANGE}\\$\${formatted_cost}\${C_RESET}"`)
    }
    push(`fi`)
    line1First = false
  }

  push(``)

  // ── LINE 2 ──────────────────────────────────────────────────────────────
  const hasLine2 = has(fields, 'ctxBar') || has(fields, 'rateBar')
  if (hasLine2) {
    const line2Prefix = has(fields, 'resetTimes') ? '├' : '╰'
    push(`# LINE 2: Bars`)
    push(`line2+="\${C_GRAY}${line2Prefix}\${C_RESET}"`)

    if (has(fields, 'ctxBar')) {
      push(`ctx_color=$(get_usage_color "$used_pct")`)
      push(`ctx_bar=$(progress_bar "$used_pct" 10)`)
      push(`line2+=" \${C_GRAY_LIGHT}[ctx]\${C_RESET} \${ctx_color}\${ctx_bar} \${used_pct}%\${C_RESET}"`)
    }

    if (has(fields, 'rateBar')) {
      push(`if [[ -n "$five_hour_pct" ]] && [[ "$five_hour_pct" != "null" ]]; then`)
      push(`    five_int=\${five_hour_pct%.*}`)
      push(`    seven_int=\${seven_day_pct%.*}`)
      push(`    five_color=$(get_usage_color "$five_int")`)
      push(`    seven_color=$(get_usage_color "$seven_int")`)
      push(`    five_bar=$(progress_bar "$five_int" 10)`)
      push(`    seven_bar=$(progress_bar "$seven_int" 10)`)
      push(`    line2+="\${SEP}\${C_GRAY_LIGHT}[5h]\${C_RESET} \${five_color}\${five_bar} \${five_int}%\${C_RESET}"`)
      push(`    line2+="\${SEP}\${C_GRAY_LIGHT}[7d]\${C_RESET} \${seven_color}\${seven_bar} \${seven_int}%\${C_RESET}"`)
      push(`fi`)
    }
    push(``)
  }

  // ── LINE 3 ──────────────────────────────────────────────────────────────
  if (has(fields, 'resetTimes')) {
    push(`# LINE 3: Reset times`)
    push(`line3+="\${C_GRAY}╰\${C_RESET}"`)
    push(`if [[ -n "$five_hour_pct" ]] && [[ "$five_hour_pct" != "null" ]]; then`)
    push(`    line3+=" \${C_GRAY_LIGHT}[↻5h]\${C_RESET} \${C_GRAY}\${five_reset_fmt:-—}\${C_RESET}"`)
    push(`    line3+="\${SEP}\${C_GRAY_LIGHT}[↻7d]\${C_RESET} \${C_GRAY}\${seven_reset_fmt:-—}\${C_RESET}"`)
    push(`fi`)
    push(``)
  }

  // ── Output ──────────────────────────────────────────────────────────────
  // Determine how many lines to output
  const outputLines = []
  outputLines.push('$line1')
  if (hasLine2) outputLines.push('$line2')
  if (has(fields, 'resetTimes')) outputLines.push('$line3')

  const formatStr = outputLines.map(() => '%s').join('\\n')
  const quotedVars = outputLines.map(v => `"${v}"`).join(' ')
  push(`printf "${formatStr}" ${quotedVars}`)

  return lines.join('\n') + '\n'
}
